version: "3"
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: docker.jfrog.io/utils/jira:0.1
    container_name: my-first-util
    working_dir: /workspace
    volumes:
      - .:/workspace
    command: tail -F /dev/null
